@startuml

title: Domain Model


abstract Asset {
        *   id : String
        idShort : String
        manufacturerId : String
        * private final Owner owner;
        manufacturerName : String
        childRelations : List<Relation>
        parentRelations : List<Relation>
        underInvestigation : boolean
        activeAlert: boolean
        qualityType : QualityType
        classification : String
        van : String
        abstract String : getSemanticDataModelId()
        abstract SemanticDataModel : getSemanticDataModel()
}
note left
    Rename Descriptions to Relations
end note


entity Relation {
       *   id : String
       idShort : String
}

enum SemanticModelType {
    SERIALPART,
    BATCH,
    JUSTINSEQUENCEPART,
    TRACTIONBATTERYCODE,
    PARTASPLANNED,
    PARTSITEINFORMATIONASPLANNED
}


entity AsBuiltAspectModel {
        manufacturingDate : Instant
        manufacturingCountry : String (iso-3)
        manufacturerPartId : String
        customerPartId : String
        nameAtManufacturer : String
        nameAtCustomer : String
}

entity SerialPart {
     partInstanceId : String
     String: getSemanticDataModelId() return partInstanceId
     SemanticModelType: getSemanticDataModel()
}

entity Batch {
     batchId : String
     String: getSemanticDataModelId() return batchId
     SemanticModelType: getSemanticDataModel()
}

entity JustInSequencePart {
     jisNumber : String
     String: getSemanticDataModelId() return jisNumber
     SemanticModelType: getSemanticDataModel()
}

entity TractionBatteryCode {
    productType: String
    tractionBatteryCode: String
    subComponents : List<TractionBatteryCode>
}

entity PartAsPlanned {
/'
    1.0.0
'/
    validityPeriodFrom : Instance
    validityPeriodTo: Instance
}

entity PartSiteInformationAsPlanned {
/'
    1.0.0
    Currently this is not ready for implementing - there is no specification right now.
'/
    functionValidFrom : Instance
    functionValidUntil : Instance
}

entity AsPlannedAspectModel {
        manufacturingDate : Instant
        manufacturingCountry : String
        manufacturerPartId : String
        customerPartId : String
        nameAtManufacturer : String
        nameAtCustomer : String
}

SemanticModelType --> Asset
Asset <|.. AsBuiltAspectModel
Asset <|.. AsPlannedAspectModel

AsBuiltAspectModel <|.. Batch
AsBuiltAspectModel <|.. SerialPart
AsBuiltAspectModel <|.. JustInSequencePart

AsPlannedAspectModel <|.. PartAsPlanned
AsPlannedAspectModel <|.. PartSiteInformationAsPlanned

Asset }o--- Relation : childRelations
Asset }o---  Relation : parentRelations

@enduml
