= Receive quality notification

This sequence diagram describes the process of receiving a quality notification from another traceability partner:

[plantuml, target=business-context_quality-investigation, format=svg]
....
include::../../../../uml-diagrams/arc42/runtime-view/quality-investigation-receive.puml[]
....

== Overview
The EDC is utilized to transmit data between sender and receiver for both sending and receiving notifications.
To be able to receive notifications by a partner you need to

* Create a notification endpoint for qualitynotifications/receive
* Create EDC assets
* Create EDC usage policies
* Create EDC contract definitions

Trace-X implements a functionality to create assets and their corresponding policies in the admin panel.

With the notification asset it is possible to enable EDC contract negotiation and EDC data transfer based on access policies defined. Only if the sender is able to find the asset in the catalog offer and perform a successful contract negotiation there will be the possibility to send a notification to the specified http endpoint on the receiver side.
