= Structure

Trace-X is divided into two components: Frontend and backend.
It roughly can be broken down into the following parts:

* Asset controllers to get asset information
* Dashboard controller to get dashboard related summed up information
* Registry controller to fetch assets from the Digital Twin Registry
* Notification controller to get notification information and create EDC notification offers
* Import controller for importing Trace-X data for data provisioning
* Contract controller to get information about contract agreements
* EDC controller to retrieve notifications
* IRS callback controller to retrieve asynchronous jobs completed by IRS
* Policy controller to retrieve information about policies
* BPN controller to retrieve information about business partners

The backend does a request to the Digital Twin Registry utilizing the registry controller. Extracted data from the response is made available through the asset controller and the dashboard controller to the frontend.

