= Operational concepts

== Administration

=== Configuration

TraceX can be configured using two mechanisms:

==== application.yml

If you build TraceX yourself, you can modify the application.yml config that is shipped with TraceX.
This file contains all possible config entries for the application.
Once the Docker image has been built, these values can only be overwritten using the Spring external config mechanism (see https://docs.spring.io/spring-boot/docs/2.1.9.RELEASE/reference/html/boot-features-external-config.html), e.g. by mounting a config file in the right path or using environment variables.

==== Helm Chart

The most relevant config properties are exposed as environment variables and must be set in the Helm chart so the application can run at all.
Check the TraceX Helm chart in Git for all available variables.

== Scaling

If the number of consumers raises, TraceX can be scaled up by using more resources for the Deployment Pod.
Those resources can be used to utilize more parallel threads to handle Job execution.

== Clustering

TraceX can run in clustered mode, as each running job is only present in one pod at a time.
Note: as soon as a resume feature is implemented, this needs to be addressed here.

== Logging

Logs are being written directly to stdout and are picked up by the cluster management.

== Monitoring

Currently, there is on monitoring supported in TraceX.
