@startuml
!include https://raw.githubusercontent.com/doubleSlashde/umltheme/main/puml-theme-doubleslash-general.puml

skinparam linetype ortho
skinparam spacing 300

title: The interfaces show how the components interact with each other and which interfaces the TraceX is providing.



component [**CatenaX-Network**] <<CX-Environment>> {
    component [**Portal**] <<System>> as PORTAL
    component [**DiscoveryFinder**] <<System>> as DiscoveryFinder
    component [**EDC Discovery Service**] <<System>> as EDCDiscoveryService
}


component [**OEM**] <<OEM-Environment>> {
    component [**EDC_Provider OEM**] <<System>> as EDCProviderOEM
    component [**Digital Twin Registry OEM**] <<System>> as DT_OEM
    component [**SubmodelServer OEM**] <<System>> as SubmodelServerOEM

    component [**TraceXApplication**] <<System>> {
    	component [**TraceX**] <<System>> as TraceX
    	component [**EDC Consumer**] <<System>> as EDC
        component [**IRS**] <<System>> as IRS
    }
}

component [**Tier1**] <<Supplier Tier1-Environment>> {
    component [**EDC_Provider Tier1**] <<System>> as EDCProviderTier1
    component [**Digital Twin Registry Tier1**] <<System>> as DT_Tier1
    component [**SubmodelServer Tier1**] <<System>> as SubmodelServerTier1
}
component [**Tier2**] <<Supplier Tier2-Environment>> {
    component [**EDC_Provider Tier2**] <<System>> as EDCProviderTier2
    component [**Digital Twin Registry Tier2**] <<System>> as DT_Tier2
    component [**SubmodelServer Tier2**] <<System>> as SubmodelServerTier2
}



actor IrsApiConsumer

IrsApiConsumer -right(0- TraceX
IrsApiConsumer -right(0- PORTAL
TraceX <.l.> PORTAL
TraceX <..> DiscoveryFinder
TraceX <..> EDCDiscoveryService
TraceX <.d.> EDC
TraceX <..> IRS

IRS <..> DiscoveryFinder
IRS <..> EDCDiscoveryService
IRS <..> EDC

EDC <..> EDCProviderOEM
EDC <..> EDCProviderTier1
EDC <..> EDCProviderTier2

EDCProviderOEM <..> SubmodelServerOEM
EDCProviderTier1 <..> SubmodelServerTier1
EDCProviderTier2 <..> SubmodelServerTier2
EDCProviderOEM <..> DT_OEM
EDCProviderTier1 <..> DT_Tier1
EDCProviderTier2 <..> DT_Tier2

@enduml
