The interfaces show how the components interact with each other and which interfaces the TraceX is providing.

Component Diagram

@startuml
skinparam monochrome true
skinparam shadowing false
skinparam spacing 50


component [**TraceXApplication**] <<System>> {
	component [**TraceX**] <<System>> as TraceX
	component [**EDC Consumer**] <<System>> as EDC

}

component [**CatenaX-Network**] <<CX-Environment>> {
    component [**IAM/KeyCloak**] <<System>> as IAM_IRS
    component [**Digital Twin Registry**] <<System>> as DT_REG
    component [**IRS**] <<System>> as IAM_DAPS
    IAM_IRS --[hidden]> DT_REG
    DT_REG --[hidden]>  IAM_DAPS
}

component [**Tier/OEM**] <<Tier/OEM-Environment>> {

    component [**EDC_Provider_OEM**] <<System>> as EDCProviderOEM
    component [**EDC_Provider_Tier1**] <<System>> as EDCProviderTier1
    component [**EDC_Provider_Tier1.1**] <<System>> as EDCProviderTier11
    component [**SubmodelServer_OEM**] <<System>> as SubmodelServerOEM
    component [**SubmodelServer_Tier1**] <<System>> as SubmodelServerTier1
    component [**SubmodelServer_Tier1.1**] <<System>> as SubmodelServerTier11
}


actor IrsApiConsumer

IrsApiConsumer -right(0- TraceX
IrsApiConsumer <.r.> IAM_IRS
TraceX <.d.> EDC
TraceX <.l.> IAM_IRS
TraceX <.> DT_REG
EDC <..> IAM_DAPS
EDC <..> EDCProviderOEM
EDC <...> EDCProviderTier1
EDC <....> EDCProviderTier11
IAM_DAPS <..> EDCProviderOEM
IAM_DAPS <...> EDCProviderTier1
IAM_DAPS <....> EDCProviderTier11
EDCProviderOEM <..> SubmodelServerOEM
EDCProviderTier1 <..> SubmodelServerTier1
EDCProviderTier11 <..> SubmodelServerTier11

@enduml
