= Policies

== Overview

=== Scenario 1: Startup interaction with the IRS policy store

The Trace-X instance defines a constraint which is required for data consumption and provisioning.
Trace-X retrieves all policies from the IRS and validates if one of the policies contains the required constraint given by Trace-X.
If a policy with the constraint exists and is valid, the process ends. If the policy is not valid, it will create one with the given constraint.

This sequence diagram describes the process of retrieving or creating policies from the IRS policy store based on the constraint given by Trace-X:

[plantuml, target=policy-startup-configuration, format=svg]
....
include::../../../uml-diagrams/arc42/runtime-view/policies/policy-startup-configuration.puml[]
....

=== Scenario 2: Startup interaction with EDC

The Trace-X instance uses the policy which includes the defined constraint and transforms it into a valid EDC policy request.
The EDC policy request will be used for creating a policy for the required notification contracts.

This sequence diagram describes the process of retrieving the correct policy by IRS policy store based on the constraint given by Trace-X and reuses it for creating an EDC policy.

[plantuml, target=policy-startup-notification-contract, format=svg]
....
include::../../../uml-diagrams/arc42/runtime-view/policies/policy-startup-notification-contract.puml[]
....

=== Scenario 3: Provisioning of notifications

The Trace-X instance uses the policy which includes the defined constraint for validation of catalog offers by the receiver EDC.

This sequence diagram describes the process of how the policy with the defined constraint will be used for validation of the catalog offers from the receiver EDC:

[plantuml, target=policy-notifications, format=svg]
....
include::../../../uml-diagrams/arc42/runtime-view/policies/policy-notifications.puml[]
....

=== Scenario 4: Provisioning of assets

The Trace-X instance uses the policy which includes the defined constraint for creating EDC assets.

This sequence diagram describes the process of how the policy with the defined constraint will be used for registering EDC data assets:

[plantuml, target=policy-assets, format=svg]
....
include::../../../uml-diagrams/arc42/runtime-view/policies/policy-assets.puml[]
....

=== Scenario 5: Updating notification offers when creating / deleting / updating policies

The Trace-X instance uses policies for creating the EDC catalog offers of notifications.
These offers will be created on the following actions:

- on Trace-X application startup
- creating a policy for the own BPN
- updating a policy for the own BPN
- deleting a policy for the own BPN

This sequence diagram describes the process of how the catalog offers are updated after policy update / create / delete:

[plantuml,target=policy-crud-notification-contract,format=svg]
....
include::../../../uml-diagrams/arc42/runtime-view/policies/policy-crud-notification-contract.puml[]
....
