# Default values for k8s-helm-example.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: product-traceability-foss

replicaCount: 1

image:
  repository: ghcr.io/catenax-ng/product-traceability-foss-backend
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "{{ .Chart.AppVersion }}"

##
## Image pull secret to create to obtain the container image
## Note: 'imagePullSecret.dockerconfigjson' takes precedence if configured together with 'imagePullSecrets'
##
imagePullSecret:
  dockerconfigjson: ""

##
## Existing image pull secret to use to obtain the container image
##
imagePullSecrets: []

nameOverride: "product-traceability-foss-backend"
fullnameOverride: "product-traceability-foss-backend"

serviceAccount:
  ##
  ## Specifies whether a service account should be created per release
  ##
  create: true
  ##
  ## Annotations to add to the service account
  ##
  annotations: {}
  ##
  ## The name of the service account to use.
  ## If not set and create is true, a name is generated using the fullname template
  ##
  name: ""


podAnnotations: { }

podSecurityContext:
  runAsUser: 10001
  seccompProfile:
    type: RuntimeDefault

# Following Catena-X Helm Best Practices @url: https://catenax-ng.github.io/docs/kubernetes-basics/helm
# @url: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 3000
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false

service:
  type: ClusterIP
  port: 8080

autoscaling:
  enabled: false

# Following Catena-X Helm Best Practices @url: https://catenax-ng.github.io/docs/kubernetes-basics/helm
# @url: https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-resource-requests-and-limits
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 512Mi

nodeSelector: { }

tolerations: [ ]

# Following Catena-X Helm Best Practices @url: https://catenax-ng.github.io/docs/kubernetes-basics/helm
# @url: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: DoesNotExist
          topologyKey: kubernetes.io/hostname

# Following Catena-X Helm Best Practices @url: https://catenax-ng.github.io/docs/kubernetes-basics/helm
# @url: https://github.com/helm/charts/blob/master/stable/nginx-ingress/values.yaml#L210
livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

##############################
# Application Configuration  #
#############################

springprofile: <springprofile>

healthCheck:
  enabled: true #<healthCheck.enabled>

traceability:
  bpn: <traceability.bpn>

datasource:
  url: <datasource.url>
  username: <datasource.username>
  password: <datasource.password>

oauth2:
  clientId: <oauth2.clientId>
  clientSecret: <oauth2.clientSecret>
  clientTokenUri: <oauth2.clientTokenUri>
  jwkSetUri: <oauth2.jwkSetUri>
  resourceClient: <oauth2.resourceClient>

edc:
  apiKey: <edc.apiKey>

postgresql:
  enabled: false #<postgresql.enabled>
  auth:
    postgresPassword: <postgresql.auth.postgresPassword>
    password: <postgresql.auth.password>
    database: <postgresql.auth.database>
    username: <postgresql.auth.username>
  architecture: standalone
  audit:
    pgAuditLog: write, ddl
    logLinePrefix: "%m %u %d "

global:
  enablePrometheus: false  #<global.enablePrometheus>
  enableGrafana: false  #<global.enableGrafana>

irs-helm:
  enabled: false  #<irs-helm.enabled>

irs-edc-consumer:
  enabled: false

pgadmin4:
  enabled: false  #<pgadmin4.enabled>
  ingress:
    enabled: false  #<pgadmin4.ingress.enabled>
