export enum ColumnType {
  //TODO: REVISIT THIS TYPE TO REDUCE POSSIBLE DUPLICATION
  ANY = 'ANY',
  ACTION = 'ACTION',
  NUMBER = 'NUMBER',
  DATE = 'DATE',
  STRING = 'STRING',
  BOOLEAN_STRING = 'BOOLEAN_STRING',
  COPY_STRING = 'COPY_STRING',
  ICON_STRING = 'ICON_STRING',
  STATUS_STRING = 'STATUS_STRING',
  ARRAY = 'ARRAY',
  BOOLEAN = 'BOOLEAN',
  TABLE = 'TABLE',
  FILE = 'FILE',
  SELECT = 'SELECT',
  TAG = 'TAG',
  LINK = 'LINK',
}
