/* 🤖 this file was generated by svg-to-ts*/
export const appIcFactory: {
  name: 'ic-factory';
  data: string;
} = {
  name: 'ic-factory',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><g fill="none" fill-rule="evenodd"><path d="M0 0h24v24H0z"/><path d="M8.364 20.182H1.956V7.495l6.408 2.758m0 2.02l-4.546-2.02v8.11h4.546m.006 0h11.812V3.823h-3.637v9.259l-6.363-2.828v2.828l-1.817-.807m-.001-4.82l6.363 2.829V2H22v18.182H8.371" fill="#444" fill-rule="nonzero"/></g></svg>`,
};
