/* 🤖 this file was generated by svg-to-ts*/
export const appIcParent: {
  name: 'ic-parent';
  data: string;
} = {
  name: 'ic-parent',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><g fill="none" fill-rule="evenodd"><path d="M0 0h24v24H0z"/><path d="M13.747.84l7.478 4.329v8.658l-3.501 2.025v2.975l-7.477 4.329-7.477-4.33V10.17l3.499-2.027.001-2.973L13.747.84zm-3.5 6.819l-5.903 3.417v6.843l5.903 3.418 5.903-3.418v-6.843L10.247 7.66zm0 3.69a3.148 3.148 0 110 6.297 3.148 3.148 0 010-6.296zm0 1.575a1.574 1.574 0 100 3.148 1.574 1.574 0 000-3.148zm3.5-10.265L7.844 6.076v1.155l2.403-1.391 7.478 4.329-.001 3.864 1.926-1.114V6.076L13.747 2.66z" fill="#444"/></g></svg>`,
};
