/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/* 🤖 this file was generated by svg-to-ts*/
export const appTrace: {
  name: 'trace';
  data: string;
} = {
  name: 'trace',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 250 250"><g fill="#000" fill-rule="nonzero"><path d="M155.691 124.39c.018-15.721-12.052-28.834-27.768-30.168-15.716-1.335-29.838 9.555-32.488 25.053-2.65 15.497 7.054 30.435 22.327 34.365v23.677c.014 12.521 10.195 22.668 22.757 22.683h41.723c12.563-.015 22.743-10.162 22.758-22.683V67.683c-.015-12.521-10.195-22.668-22.758-22.683h-60.687c-4.19 0-7.586 3.385-7.586 7.561s3.396 7.561 7.586 7.561h60.687c4.19 0 7.586 3.385 7.586 7.56v109.635c0 4.176-3.396 7.561-7.586 7.561H140.52c-4.19 0-7.586-3.385-7.586-7.56V153.64c13.38-3.453 22.733-15.474 22.758-29.25zm-45.515 0c-.015-8.315 6.708-15.082 15.05-15.148 8.342-.067 15.173 6.592 15.292 14.905.119 8.314-6.519 15.164-14.86 15.335-.106 0-.204-.03-.31-.03-.107 0-.205.026-.311.03-8.246-.169-14.847-6.871-14.861-15.092zM8 250c4.418 0 8-3.383 8-7.556v-18.888c0-4.173-3.582-7.556-8-7.556s-8 3.383-8 7.556v18.888C0 246.617 3.582 250 8 250z"/><path d="M226.364 0H22.636C10.141.015.015 10.148 0 22.653V177.45A7.548 7.548 0 007.545 185a7.548 7.548 0 007.546-7.551V22.653a7.548 7.548 0 017.545-7.551h203.728a7.548 7.548 0 017.545 7.551v15.102a7.548 7.548 0 007.546 7.551 7.548 7.548 0 007.545-7.55V22.652C248.985 10.148 238.86.015 226.364 0z"/><path d="M242.407 75.37a7.593 7.593 0 00-7.592 7.593v144.26c0 4.192-3.4 7.592-7.593 7.592H67.778a7.593 7.593 0 01-7.593-7.593V67.778c0-4.193 3.4-7.593 7.593-7.593h7.592a7.593 7.593 0 000-15.185h-7.592C55.204 45.015 45.015 55.204 45 67.778v159.444c.015 12.574 10.204 22.763 22.778 22.778h159.444c12.574-.015 22.763-10.204 22.778-22.778V82.963c0-4.193-3.4-7.593-7.593-7.593z"/><circle cx="8" cy="200" r="8"/><circle cx="242" cy="60" r="8"/><circle cx="99" cy="53" r="8"/></g></svg>`,
};
