/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/* 🤖 this file was generated by svg-to-ts*/
export const appCar: {
  name: 'car';
  data: string;
} = {
  name: 'car',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 318 123"><g fill-rule="evenodd"><path d="M27.95 100.23l-19.09-.933c-3.433-.528-5.742-1.65-6.929-3.365-1.186-1.715-1.6-5.229-1.238-10.54l5.711-46.774c.456-2.675 1.275-4.524 2.456-5.547 1.181-1.023 3.759-1.713 7.732-2.071H36L78.136 8.058c6.836-2.99 12.36-4.884 16.572-5.68C98.921 1.58 105.835 1.12 115.452 1c9.486-.162 17.296-.162 23.428 0 3.223.085 7.29.379 12.389.628 3.068.15 8.465.4 16.192.75 7.084.743 12.799 1.925 17.145 3.547s10.728 4.954 19.146 9.995L249 44c10.312.897 17.683 1.644 22.115 2.24 4.43.598 9.935 1.585 16.514 2.963 5.594 1.699 9.785 3.676 12.574 5.93 2.79 2.255 6.11 6.659 9.964 13.212 2.207 4.788 3.721 8.501 4.545 11.139.823 2.637 1.474 6.582 1.953 11.835.11 2.719-.303 4.713-1.24 5.983-.937 1.27-3.113 2.17-6.527 2.698h-20.76M62 58c23.196 0 36.088 19.034 36.088 42.23H27.95C27.95 77.034 38.804 58 62 58zm190.05 0c23.195 0 36.087 18.804 36.087 42H218.04c0-23.196 10.814-42 34.01-42zM157 8l.68.003c12.602.103 20.513 3.12 31.32 9.997l30 19-71-5V8h9z"/><path d="M253 62c17.308 0 30 12.692 30 30 0 16.154-12.692 30-30 30-16.154 0-30-13.846-30-30 0-17.308 13.846-30 30-30zm-.08 15c8.12 0 15.08 6.96 15.08 15.08 0 8.12-6.96 13.92-15.08 13.92-8.12 0-13.92-5.8-13.92-13.92 0-8.12 5.8-15.08 13.92-15.08zM62 62c17.308 0 30 12.692 30 30 0 16.154-12.692 30-30 30-16.154 0-30-13.846-30-30 0-17.308 13.846-30 30-30zm-.08 15C70.04 77 77 83.96 77 92.08 77 100.2 70.04 106 61.92 106 53.8 106 48 100.2 48 92.08 48 83.96 53.8 77 61.92 77z"/></g></svg>`,
};
