/* 🤖 this file was generated by svg-to-ts*/
export const appArrowDownSFill: {
  name: 'arrow-down-s-fill';
  data: string;
} = {
  name: 'arrow-down-s-fill',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill="none" d="M0 0h24v24H0z"/><path d="M12 16l-6-6h12z"/></svg>`,
};
