/* 🤖 this file was generated by svg-to-ts*/
export const appIcMissingSomeParts: {
  name: 'ic-missing-some-parts';
  data: string;
} = {
  name: 'ic-missing-some-parts',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><g fill="none" fill-rule="evenodd"><path d="M12 13h12v12H12z"/><path d="M18.433 14.5l4.763 8.25a.5.5 0 01-.433.75h-9.526a.5.5 0 01-.433-.75l4.763-8.25a.5.5 0 01.866 0zm-4.33 8h7.794L18 15.75l-3.897 6.75zM17.5 21h1v1h-1v-1zm0-3.5h1V20h-1v-2.5z" fill="#FFAD1F"/><g><path d="M0 0h24v24H0z"/><path d="M12 1l9.5 5.5V13h-2V7.653L12 3.311 4.5 7.653v8.694l7.5 4.342V23l-9.5-5.5v-11L12 1zm0 7a4 4 0 110 8 4 4 0 010-8zm0 2a2 2 0 100 4 2 2 0 000-4z" fill="#444"/></g></g></svg>`,
};
