/* 🤖 this file was generated by svg-to-ts*/
export const appIcAllPartsAvailable: {
  name: 'ic-all-parts-available';
  data: string;
} = {
  name: 'ic-all-parts-available',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><g fill="none" fill-rule="evenodd"><path d="M0 0h24v24H0z"/><path d="M12 1l9.5 5.5V13h-2V7.653L12 3.311 4.5 7.653v8.694l7.5 4.342V23l-9.5-5.5v-11L12 1zm0 7a4 4 0 110 8 4 4 0 010-8zm0 2a2 2 0 100 4 2 2 0 000-4z" fill="#444"/><g><path d="M12 13h12v12H12z"/><path d="M18 24a5 5 0 110-10 5 5 0 010 10zm0-1a4 4 0 100-8 4 4 0 000 8zm-.498-2l-2.122-2.122.707-.707 1.415 1.415 2.828-2.829.707.707L17.501 21z" fill="#3DB014"/></g></g></svg>`,
};
