/* 🤖 this file was generated by svg-to-ts*/
export const appArrowLeftUpLine: {
  name: 'arrow-left-up-line';
  data: string;
} = {
  name: 'arrow-left-up-line',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill="none" d="M0 0h24v24H0z"/><path d="M9.414 8l8.607 8.607-1.414 1.414L8 9.414V17H6V6h11v2z"/></svg>`,
};
