/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/* 🤖 this file was generated by svg-to-ts*/
export const appIcFactory: {
  name: 'ic-factory';
  data: string;
} = {
  name: 'ic-factory',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><g fill="none" fill-rule="evenodd"><path d="M0 0h24v24H0z"/><path d="M8.364 20.182H1.956V7.495l6.408 2.758m0 2.02l-4.546-2.02v8.11h4.546m.006 0h11.812V3.823h-3.637v9.259l-6.363-2.828v2.828l-1.817-.807m-.001-4.82l6.363 2.829V2H22v18.182H8.371" fill="#444" fill-rule="nonzero"/></g></svg>`,
};
