/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/* 🤖 this file was generated by svg-to-ts*/
export const appIcMissingAllParts: {
  name: 'ic-missing-all-parts';
  data: string;
} = {
  name: 'ic-missing-all-parts',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><g fill="none" fill-rule="evenodd"><path d="M0 0h24v24H0z"/><path d="M12 1l9.5 5.5V13h-2V7.653L12 3.311 4.5 7.653v8.694l7.5 4.342V23l-9.5-5.5v-11L12 1zm0 7a4 4 0 110 8 4 4 0 010-8zm0 2a2 2 0 100 4 2 2 0 000-4z" fill="#444"/><g><path d="M12 13h12v12H12z"/><path d="M18 24a5 5 0 110-10 5 5 0 010 10zm0-1a4 4 0 100-8 4 4 0 000 8zm-.5-2.5h1v1h-1v-1zm0-4h1v3h-1v-3z" fill="#B21014"/></g></g></svg>`,
};
