/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/* 🤖 this file was generated by svg-to-ts*/
export const appSkull2Fill: {
  name: 'skull-2-fill';
  data: string;
} = {
  name: 'skull-2-fill',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill="none" d="M0 0h24v24H0z"/><path d="M12 2c5.523 0 10 4.477 10 10v3.764a2 2 0 01-1.106 1.789L18 19v1a3 3 0 01-2.824 2.995L14.95 23a2.5 2.5 0 00.044-.33L15 22.5V22a2 2 0 00-1.85-1.995L13 20h-2a2 2 0 00-1.995 1.85L9 22v.5c0 .171.017.339.05.5H9a3 3 0 01-3-3v-1l-2.894-1.447A2 2 0 012 15.763V12C2 6.477 6.477 2 12 2zm-4 9a2 2 0 100 4 2 2 0 000-4zm8 0a2 2 0 100 4 2 2 0 000-4z"/></svg>`,
};
