/* 🤖 this file was generated by svg-to-ts*/
export const appFlag2Fill: {
  name: 'flag-2-fill';
  data: string;
} = {
  name: 'flag-2-fill',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path fill="none" d="M0 0h24v24H0z"/><path d="M2 3h19.138a.5.5 0 01.435.748L18 10l3.573 6.252a.5.5 0 01-.435.748H4v5H2V3z"/></svg>`,
};
