/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/* 🤖 this file was generated by svg-to-ts*/
export const appIwpTextDocBlue: {
  name: 'iwp-text-doc-blue';
  data: string;
} = {
  name: 'iwp-text-doc-blue',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 500"><g fill="#6C7C97"><path d="M403.646 42.104H172.424c-.076 0-.139.042-.215.043-4.59-.299-9.202 1.437-12.45 4.941l-83.405 89.65a15.609 15.609 0 00-4.072 12.456c-.006.191-.109.351-.109.544v297.119c0 8.627 6.999 15.625 15.625 15.625h315.846c8.628 0 15.625-6.998 15.625-15.625V57.729c.002-8.626-6.997-15.625-15.623-15.625zM155.579 97.463v34.292h-31.901l31.901-34.292zm232.442 333.77H103.424V163.004h67.779c8.626 0 15.625-6.999 15.625-15.625V73.354H388.02v357.879h.001z"/><path d="M145.713 197.613h146.982v30H145.713zM145.713 274.641h208.982v30H145.713zM145.713 351.641h208.982v30H145.713z"/></g></svg>`,
};
