/* 🤖 this file was generated by svg-to-ts*/
export const appIcQualityType: {
  name: 'ic-quality-type';
  data: string;
} = {
  name: 'ic-quality-type',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><g fill="none" fill-rule="evenodd"><path d="M0 0h24v24H0z"/><path d="M0 0h24v24H0z"/><path d="M0 0h24v24H0z"/><path d="M12 1a8 8 0 017.134 11.624l3.33 5.768a1 1 0 01-.819 1.5l-.112-.002-2.933-.19-1.302 2.636a1 1 0 01-1.701.15l-.062-.094-3.12-5.403a8.131 8.131 0 01-.832 0l-3.118 5.403a1 1 0 01-1.708.041l-.055-.097L5.4 19.7l-2.933.19a1 1 0 01-.981-1.399l.05-.1 3.33-5.768A8 8 0 0112 1zm5.87 13.435a8.005 8.005 0 01-3.368 2.166l1.83 3.172.771-1.556a1 1 0 01.828-.554h.133l1.733.111zm-11.74 0l-1.928 3.338 1.734-.11a1 1 0 01.894.439l.067.115.77 1.556L9.498 16.6a8.005 8.005 0 01-3.368-2.166zM12 3a6 6 0 100 12 6 6 0 000-12z" fill="#444"/></g></svg>`,
};
