/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

/* 🤖 this file was generated by svg-to-ts*/

export type myIcons =
  | 'add-circle-line'
  | 'add-fill'
  | 'admin-line'
  | 'alarm-warning-line'
  | 'alert-line'
  | 'arrow-down-line'
  | 'arrow-down-s-fill'
  | 'arrow-down-s-line'
  | 'arrow-left-down-line'
  | 'arrow-left-line'
  | 'arrow-left-right-fill'
  | 'arrow-left-s-fill'
  | 'arrow-left-s-line'
  | 'arrow-left-up-line'
  | 'arrow-right-down-line'
  | 'arrow-right-line'
  | 'arrow-right-s-fill'
  | 'arrow-right-s-line'
  | 'arrow-right-up-line'
  | 'arrow-up-line'
  | 'arrow-up-s-fill'
  | 'arrow-up-s-line'
  | 'bar-chart-2-fill'
  | 'calendar-line'
  | 'car-components-2'
  | 'car-components'
  | 'car'
  | 'check-fill'
  | 'checkbox-circle-fill'
  | 'checkbox-circle-line'
  | 'close-circle-fill'
  | 'close-circle-line'
  | 'close-fill'
  | 'dashboard-fill'
  | 'dashboard-line'
  | 'delete-bin-line'
  | 'download-line'
  | 'error-warning-fill'
  | 'error-warning-line'
  | 'exchange-box-fill'
  | 'eye-line'
  | 'file-copy-fill'
  | 'file-copy-line'
  | 'file-excel-2-fill'
  | 'file-excel-2-line'
  | 'file-excel-fill'
  | 'file-excel-line'
  | 'file-pdf-fill'
  | 'file-pdf-line'
  | 'file-search-line'
  | 'filter-2-fill'
  | 'filter-fill'
  | 'flag-2-fill'
  | 'flag-2-line'
  | 'flag-fill'
  | 'flag-line'
  | 'folder-2-line'
  | 'folder-5-fill'
  | 'gen-fit'
  | 'ic-alert'
  | 'ic-all-parts-available'
  | 'ic-car-component-v-2-5'
  | 'ic-car-component-v-2'
  | 'ic-car-v-2'
  | 'ic-co-2'
  | 'ic-dashboard'
  | 'ic-factory'
  | 'ic-missing-all-parts'
  | 'ic-missing-some-parts'
  | 'ic-parent'
  | 'ic-quality-type'
  | 'ic-search'
  | 'indeterminate-circle-line'
  | 'information-line'
  | 'iwp-text-doc-blue'
  | 'layout-masonry-fill'
  | 'layout-masonry-line'
  | 'line-chart-fill'
  | 'logout-circle-line'
  | 'mail-fill'
  | 'mail-line'
  | 'more-line'
  | 'no-data-illustration'
  | 'partchain'
  | 'pencil-line'
  | 'question-fill'
  | 'question-line'
  | 'search-fill'
  | 'search-line'
  | 'settings-3-line'
  | 'settings-line'
  | 'share-line'
  | 'skull-2-fill'
  | 'spam-line'
  | 'spy-fill'
  | 'spy-line'
  | 'steering-2-fill'
  | 'trace';
export interface MyIcon {
  name: myIcons;
  data: string;
}
