= Policy management

To ensure data sovereignty within Trace-X, companies can create policies with constraints to ensure that their data is only shared with companies that match their requirements.

Policies will be used by the EDC to initiate contract negotiations. During the negotiation the EDC will compare the policies of both companies. Only if both policies are valid and the included constraints match, the data will be shared. This applies for sending and receiving of notifications and parts.

After deploying Trace-X, no policies are defined for any BPNs yet. Instead, Trace-X will set up default policies. This ensures that the basic functionality of Trace-X works.
However, to be sure that data is shared only with companies that match one's requirements, an administrator must set up policies before sending and receiving data.

The policies used for sending and receiving notifications and parts have an identical data format, so they can be used for each process interchangeably.
The processes itself are different and will be explained in this section.

== Policy Types

The EDC connector MUST provide a possibility to restrict the access of a data asset to specific business partners by attribute(s), e.g. represented as a VC.
The connector MUST restrict the data usage to partners and purposes for a specific use case.

There are two policy types used.

* Access
* Usage

As specified by the https://github.com/International-Data-Spaces-Association/ids-specification[Dataspace Protocol] one data asset MUST refer to at least one usage policy, expressed in ODRL.
For additional information refer to the https://eclipse-tractusx.github.io/docs-kits/kits/Connector%20Kit/Adoption%20View/connector_kit_adoption_view[Connector KIT]

== Policies for sending and receiving parts
[plantuml, target=data-sovereignty-publish-assets, format=svg]
....
include::../../../../uml-diagrams/arc42/runtime-view/data-sovereignty/data-sovereignty-publishing-assets.puml[]
....

[cols="1,5"]
|===
|1,2,3,4
|Policies can be created by user with role 'Admin' at any time in the administration section of Trace-X. The policy is created to later used for publishing parts in the current company context. Policies are stored in the PolicyStore which is a shared component used by Trace-X [A] and Item Relationship Service (IRS) for storing usage and access policies.

|5,6
|User with role 'Admin' imports assets in the administration section of Trace-X [A]. Parts can be imported at any time in the parts section of Trace-X. They will be stored locally at first. https://github.com/eclipse-tractusx/traceability-foss/tree/main/tx-backend/testdata[Testdata for asset import]

|7,8,9
|User with role 'Admin' selects parts in transient state in application and publishes them. The user must choose the policy that is used for the contract negotiation of the selected parts.

|10,11
|The parts are created in the EDC. (POST /v3/assets)

|12,13
|In case the PolicyDefinition does not exist yet, a new PolicyDefinition is created in the EDC [A].

|14,15
|A contractDefinition is created using the provided policyDefinition.

|16,17
|Each part is created as a Asset Administration Shell Descriptor in the Digital Twin Registry (DTR). This holds all the data of the part including the globalAssetId.

|18,19,20,21
|Policies can be created by user with role 'Admin' at any time in the administration section of Trace-X. When synchronizing parts, the respective policies for connected BPNLs will be used.

|22
|Trace-X [B] wants to synchronize parts and retrieve available ones from connected BPNs. In this case Trace-X [A] and Trace-X [B] have an established connection.

|23,24
|Trace-X [B] requests all Asset Administration Shell Descriptors in the DTR of Trace-X [A].

|25
|The globalAssetIds are extracted from the Shell Descriptors.

|26
|For part synchronization a job is started in the IRS using the globalAssetIds from the previous step.

|27,28
|IRS requests the catalogOffer for all globalAssetsIds.

|29,30
|IRS requests policies defined for the BPNL of Trace-X [A] in the PolicyStore of Trace-X [B].

|31
|Now that the IRS has all the relevant policies of both companies, it can start comparing the linked policy in the catalogOffer of each part to the policy list of Trace-X [B]. This works by comparing the included constraints logically.

|32,33,34,35
|If the policy of the part matches with any policy of Trace-X [A], a contract agreement is created for both Trace-X [A] and Trace-X [B]. It can be viewed in the administration section of Trace-X and documents the data exchange.

|ref import part data
|Now that the contract negotiation was successful, the part data can be imported. This process is documented in the data consumption section.

|36,37
|In case the policy does not match, IRS creates a tombstone and sends a job response to Trace-X [B].

|38
|IRS responds to the Trace-X [B] instance after completing job processing. The contractAgreementId for the asset is available in the job response.
|===

It's possible to publish parts with different policies. For this, the user must only publish a limited selection of parts for which he can select a policy. For parts that must be published with different policies, the user can repeat the process.

**Note**:
For more detailed information concerning the functionality of IRS please refer to the https://eclipse-tractusx.github.io/item-relationship-service/docs/[IRS documentation]

**[Work-in-progress]** The user may also choose parts that have already been published - they can be republished with a different policy. The process for this is identical to the regular publishing process.

== Policies for sending and receiving notifications
[plantuml, target=data-sovereignty-notifications, format=svg]
....
include::../../../../uml-diagrams/arc42/runtime-view/data-sovereignty/data-sovereignty-notifications.puml[]
....

[cols="1,5"]
|===
|1
|Policies can be created by administrators at any time in the administration section of Trace-X. In order for policies to be used for notifications the administrator must pay attention to the BPN selection of the policies, as Trace-X will choose notification policies based on that.

|2
|The user sends a notification to a connected BPN.

|3
|First, Trace-X checks the configured policies for any valid (not expired) policies that have the BPN of the receiver in their BPN selection. **There can only be one valid policy for each BPN.**

|4
|Trace-X takes the appropriate policyDefinition.

|5
|Trace-X requests the catalog of the receiver BPN from their EDC. The catalog contains all policies of the BPN including the policies they use for sending and receiving policies.

|6
|The receiver EDC returns the catalog.

|7
|Trace-X extracts the required policy definition for receiving notifications from the catalog. If the receiving BPN has multiple valid ones, they all will be extracted in a list.

|8
|Trace-X compares the extracted policies with its own policy definition. This works by comparing the included constraints logically.

|9, 10
|If any of the policies match, a contract agreement is created and shared with the receiving EDC and the EDC of the sender. It can be viewed in the administration section of Trace-X.

|11
|Finally, the notification will be sent to the receiving EDC.

|12
|If no policies match, an error will be returned to the user.
|===

=== No policies defined for receiver when sending notifications

[plantuml, target=data-sovereignty-notifications-policy-change, format=svg]
....
include::../../../../uml-diagrams/arc42/runtime-view/data-sovereignty/data-sovereignty-notifications-policy-change.puml[]
....

If no policies are configured for the receiving BPN and a notification is sent to that BPN, the default policy of Trace-X is used as a backup. If the default policy is accepted by the receiving BPN, the process can continue as normally and the notification can be sent. When the policy does not match and the notification can't be sent, an administrator can create policies for the receiving BPN. Then the notification can be resent and will use the new policy.

=== Expired policy when sending notifications

[plantuml, target=data-sovereignty-expired-policy, format=svg]
....
include::../../../../uml-diagrams/arc42/runtime-view/data-sovereignty/data-sovereignty-notifications-policy-expired.puml[]
....

Policies always have an expiration time defined by the 'validUntil' timestamp. When a notification is sent and there are policies configured for the selected BPN with an expiration time in the past, Trace-X will throw an error. In that case, an administrator must update or recreate the policy. Then the policy can be resent.

=== Testing policies

In order to test the functionality of policies, an administrator can create a policy with test constraints for connected BPNs. When sending notifications to that BPN, the process should be blocked.

To fix it, the administrator either has to replace the policy with a valid policy or the connected BPN can create an identical policy with the same test constraints. Sending the notification will work after this was done.

The same applies for sending and receiving parts only then the user must choose the created test policy manually.

An example testing process will be described here with two companies Trace-X A and Trace-X B:

==== Step 1

In the initial state of Trace-X, only the default policy exists:

image::https://raw.githubusercontent.com/eclipse-tractusx/traceability-foss/main/docs/src/images/arc42/runtime-view/data-sovereignty/step-1.svg[]

The catalog offer contains the policy definition of the default policy:

image::https://raw.githubusercontent.com/eclipse-tractusx/traceability-foss/main/docs/src/images/arc42/runtime-view/data-sovereignty/step-1-1.svg[]

In this state both companies can send notifications to each other.

==== Step 2

In this example Trace-X B creates a new policy:

image::https://raw.githubusercontent.com/eclipse-tractusx/traceability-foss/main/docs/src/images/arc42/runtime-view/data-sovereignty/step-2.svg[]

image::https://raw.githubusercontent.com/eclipse-tractusx/traceability-foss/main/docs/src/images/arc42/runtime-view/data-sovereignty/step-2-1.svg[]

Once created, the catalog offer will be updated using this policy:

image::https://raw.githubusercontent.com/eclipse-tractusx/traceability-foss/main/docs/src/images/arc42/runtime-view/data-sovereignty/step-2-2.svg[]

==== Step 3

Since the catalog offer of Trace-X B was updated, Trace-X A won't be able to send notifications to Trace-X B anymore:

image::https://raw.githubusercontent.com/eclipse-tractusx/traceability-foss/main/docs/src/images/arc42/runtime-view/data-sovereignty/step-3.svg[]

Trace-X A will take its own default policy and compare it to the catalog offer provided by Trace-X B, which will result in a mismatch.

==== Step 4

Since Trace-X B has no policy defined for Trace-X A's BPN, it will compare its own default policy with the catalog offer provided Trace-X A which is identical to the default policy. So Trace-X B can still send notifications to Trace-X A:

image::https://raw.githubusercontent.com/eclipse-tractusx/traceability-foss/main/docs/src/images/arc42/runtime-view/data-sovereignty/step-4.svg[]

==== Step 5

Now Trace-X A can create a new policy using the same constraints as Trace-X B's policy:

image::https://raw.githubusercontent.com/eclipse-tractusx/traceability-foss/main/docs/src/images/arc42/runtime-view/data-sovereignty/step-5.svg[]

image::https://raw.githubusercontent.com/eclipse-tractusx/traceability-foss/main/docs/src/images/arc42/runtime-view/data-sovereignty/step-5-1.svg[]

This policy will now be used when sending notifications to Trace-X B. Trace-X A's catalog offer is unchanged.

==== Step 6

Trace-X A can now send notifications to Trace-X B again, since the policy matches with the provided catalog offer:

image::https://raw.githubusercontent.com/eclipse-tractusx/traceability-foss/main/docs/src/images/arc42/runtime-view/data-sovereignty/step-6.svg[]
