@startuml
skinparam monochrome true
skinparam shadowing false
skinparam nodesep 100
skinparam ranksep 20

actor "User" as User
component [**Trace-X**] <<System>> as Trace

node "Portal" {
    [**Portal**] <<Component>> as PORTAL
}

node "IAM" {
    [**Keycloak**] <<Component>> as KIAM
}

interface "TRACE API" as TAPI
interface "OIDC" as IAMAPI
interface "Portal API" as PAPI

User -( TAPI
TAPI - Trace
Trace --( PAPI
PAPI -- PORTAL
Trace --right( IAMAPI
PORTAL --( IAMAPI
KIAM -- IAMAPI
@enduml
