@startuml
!define ENTITY class
!define TABLE class
!define PRIMARY_KEY_FIELD field
!define FIELD field
!define FOREIGN_KEY_FIELD field
!define GENERATED_FIELD field

ENTITY public.digital_twin_registry_entry {
    + aas_id : varchar(255)
    ttl : int
    created : timestamp
    updated : timestamp
    expiry_date : timestamp
    actor : varchar(255)
    digital_twin_type : varchar(255)
    bpn : varchar(255)
    global_asset_id : varchar(255)
}

public.digital_twin_registry_entry }-- public.assets_as_built : global_asset_id = id
public.digital_twin_registry_entry }-- public.assets_as_planned : global_asset_id = id

ENTITY public.assets_as_built {
    + id : varchar(255)
    customer_part_id : varchar(255)
    id_short : varchar(255)
    manufacturer_id : varchar(255)
    manufacturer_name : varchar(255)
    manufacturer_part_id : varchar(255)
    manufacturing_country : varchar(255)
    name_at_customer : varchar(255)
    name_at_manufacturer : varchar(255)
    quality_type : varchar(50)
    van : varchar(255)
    owner : varchar(50)
    semantic_model_id : varchar(255)
    semantic_data_model : varchar(50)
    classification : varchar(255)
    product_type : varchar(255)
    traction_battery_code : varchar(255)
    manufacturing_date : timestamp
    import_state : varchar(30)
    import_note : varchar(100)
    policy_id : varchar(100)
    tombstone : varchar
    contract_agreement_id : varchar(255)
    created : timestamp
    ttl : integer
    expiration_date: timestamptz
}




TABLE public.assets_as_built_childs {
  + asset_as_built_id : varchar(255)
  id : varchar(255)
  id_short : varchar(255)
}

TABLE public.assets_as_built_parents {
  + asset_as_built_id : varchar(255)
  id : varchar(255)
  id_short : varchar(255)
}


TABLE public.assets_as_built_notifications {
  + notification_id : int8
  + asset_id : varchar(255)
}



TABLE public.assets_as_built_notification_messages {
  + notification_message_id : varchar(255)
  + asset_id : varchar(255)
}


ENTITY public.traction_battery_code_subcomponent {
  traction_battery_code : varchar(255)
  subcomponent_traction_battery_code : varchar(255)
  product_type : varchar(255)
}


ENTITY public.notification {
  + id : int8 GENERATED
  title : varchar(255)
  type : varchar(50)
  status : varchar(50)
  description : varchar(1000)
  createdBy: varchar
  createdByName: varchar
  createdDate: timestamp
  updatedDate : timestamp
  assetIds: varchar
  channel: boolean
  sendTo: varchar
  sentToName: varchar
  severity: int4
  targetDate: instant
  messages: notification_message
}


ENTITY public.notification_message {
   + id : varchar(255)
    sentBy: varchar
    sentByName: varchar

    contract_agreement_id : varchar(255)

    edc_url : varchar(255)
    notification_reference_id : varchar(255)
    send_to : varchar(255)
    created_by : varchar(255)
    notification_id : bigint,
    created_by_name : varchar(255)
    send_to_name : varchar(255)
    edc_notification_id : varchar(255)
    status : varchar(255)
    message_date: instant
    error_message : varchar
    message: varchar
    message_id : varchar(255)
}



TABLE public.assets_as_planned_childs {
  asset_as_planned_id : varchar(255)
  id : varchar(255)
  id_short : varchar(255)
}


  ENTITY public.submodel {
    + id : varchar(255)
    submodel : varchar
  }

ENTITY public.submodel_payload
{
    + id : varchar(255)
    json : varchar
    aspect_type : varchar(255)
    asset_as_built_id : varchar(255)
    asset_as_planned_id : varchar(255)

}

ENTITY public.assets_as_planned {
  + id : varchar(255)
    id_short : varchar(255)
    manufacturer_part_id : varchar(255)
    name_at_manufacturer varchar(255)
    quality_type : varchar(50)
    classification : varchar(255)
    owner : varchar(50)
    semantic_data_model : varchar(50)
    function : varchar(255)
    manufacturer_name : varchar(255)
    van : varchar(255)
    semantic_model_id : varchar(255)
    catenax_site_id : varchar(255)
    function_valid_from : timestamp
    function_valid_until : timestamp
    validity_period_from : timestamp
    validity_period_to : timestamp
    manufacturer_id : varchar(255)
    import_state : varchar(30)
    import_note : varchar(100)
    policy_id : varchar(100)
    tombstone : varchar
    contract_agreement_id : varchar(255)
    created : timestamp
    ttl : integer
    expiration_date: timestamptz
  }

   ENTITY public.bpn_storage {
     + manufacturer_id : varchar(255)
     manufacturer_name : varchar(255)
     url : varchar(255)
     created : timestamptz
     updated : timestamptz
   }

public.assets_as_built -l public.submodel_payload: FOREIGN_KEY: asset_as_built_id
public.assets_as_built -{ public.traction_battery_code_subcomponent: FOREIGN_KEY: traction_battery_code
public.assets_as_built -u-{ public.assets_as_built_parents: FOREIGN_KEY: asset_as_build_id
public.assets_as_built -u-{ public.assets_as_built_childs: FOREIGN_KEY: asset_as_build_id
public.assets_as_built }--{ public.assets_as_built_notifications: FOREIGN_KEY: asset_id
public.assets_as_built }--{ public.assets_as_built_notification_messages: FOREIGN_KEY: asset_id


public.notification_message }-l- public.notification: FOREIGN_KEY: notification_id
public.notification_message }-{ public.assets_as_built_notification_messages: FOREIGN_KEY: notification_message_id
public.notification }-l{ public.assets_as_built_notifications: FOREIGN_KEY: notification_id


public.assets_as_planned -u-{ public.assets_as_planned_childs: FOREIGN_KEY: asset_as_planned_id
public.assets_as_planned - public.submodel_payload: FOREIGN_KEY: asset_as_planned_id

TABLE public.orders {
  + id : varchar(255)
  status : varchar(11)
  message : text
  created_at : timestamptz
  updated_at : timestamptz
}

TABLE public.order_configuration {
  + id : bigint
  order_id : varchar(255)
  batch_size : integer
  timeout_ms : integer
  job_timeout_ms : integer
  created_at : timestamptz
  updated_at : timestamptz
}

TABLE public.trigger_configuration {
  + id : bigint
  cron_expression_register_order_ttl_reached : text
  cron_expression_map_completed_orders : text
  part_ttl : integer
  aas_ttl : integer
  created_at : timestamptz
  updated_at : timestamptz
}

public.order_configuration -l public.orders: FOREIGN_KEY: order_id

  @enduml
