@startuml
title
    ==GET api/contracts
end title

autonumber "<B>[00]"

participant "Trace-X Frontend" as FE order 0
participant "Trace-X Backend" as BE order 1
participant "Trace-X EDC Client Library" as TXEDC order 2
participant "EDC" as EDC order 3

FE -> BE: GET api/contracts
activate BE
BE -> TXEDC: POST tx-edc/management/v2/contractagreements/request
activate TXEDC
autonumber stop
TXEDC -> EDC: Get contractAgreements
activate EDC
EDC --> TXEDC: contractAgreements
deactivate EDC
TXEDC --> BE: JSON response
autonumber resume
deactivate TXEDC
BE -> BE: First mapping
activate BE
deactivate BE
loop for all contractAgreementIds
BE -> TXEDC: GET tx-edc/management/v2/contractagreements/{contractAgreementId}/negotiation
activate TXEDC
autonumber stop
TXEDC -> EDC: Get contractNegotiation
activate EDC
EDC --> TXEDC: contractNegotiation
deactivate EDC
TXEDC --> BE: JSON response
autonumber resume
deactivate TXEDC
BE -> BE: Second mapping
activate BE
deactivate BE
end
BE --> FE: JSON response
deactivate BE

@enduml
