@startuml
title
    ==POST api/contracts/request
end title

autonumber "<B>[00]"

participant "Trace-X Frontend" as FE order 0
participant "Trace-X Backend" as BE order 1
participant "Trace-X Database" as DB order 2
participant "EDC" as EDC order 3

FE -> BE: POST api/contracts/request (limit, offset, sort, filter)

activate BE
BE -> DB: Fetch requested distinct contractAgreementIds
activate DB
autonumber stop
DB --> BE: List(contractAgreementIds)
autonumber resume
deactivate DB

BE -> EDC: POST tx-edc/management/v2/contractagreements/request \nfiltered by contractAgreementIds
activate EDC
autonumber stop
EDC --> BE: JSON response
autonumber resume
deactivate EDC
BE -> BE: Extract contractSigningDate, policy
activate BE
deactivate BE

loop for all contractAgreementIds
BE -> EDC: GET tx-edc/management/v2/contractagreements/{contractAgreementId}/negotiation
activate EDC
autonumber stop
EDC --> BE: JSON response
autonumber resume
deactivate EDC
BE -> BE: Extract id, counterPartyAddress, state
activate BE
deactivate BE
end

autonumber stop
BE --> FE: JSON response
autonumber resume
deactivate BE

@enduml
