@startuml
title
    == Request ContractResponse (Contract Agreements)
end title

autonumber "<B>[00]"
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName "Architects daughter"
skinparam linetype ortho

participant "Trace-X \n Frontend" as FE order 0
participant "Trace-X \n Backend" as BE order 1
participant "Trace-X \n Database" as DB order 2
participant "EDC \n ManagementAPI" as TXEDC order 3

FE -> BE: Request for ContractResponse
note left
    GET /contracts by filterExpression
end note

loop for each contract agreement
    activate BE
        BE -> DB: Query contractAgreementId for assetId
    activate DB
        DB --> BE: result contractAgreementId
    deactivate DB

    BE -> TXEDC: GET contractagreements
    note left
        GET edc/management/v2/contractagreements/{contractAgreementId}
    end note
    activate TXEDC
    TXEDC --> BE: return contract agreements
    deactivate TXEDC
    BE -> BE: Extract contractSigningDate, policy
    activate BE
    deactivate BE

    BE -> TXEDC: GET edc/management/v2/contractagreements/{contractAgreementId}/negotiation
    activate TXEDC
    TXEDC --> BE: Gets a contract negotiation with the given contract agreement ID
    deactivate TXEDC
    BE -> BE: Extract id, counterPartyAddress, state
    activate BE
    BE -> BE : Create ContractResponse
    deactivate BE

end loop

BE --> FE: List of ContractResponses for filterExpression
deactivate BE
autonumber stop
@enduml
