/*
 * Copyright 2021 The PartChain Authors. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 🤖 this file was generated by svg-to-ts*/

import { MyIcon } from './svg/my-icons.model';

export type IconNameSubset<T extends Readonly<MyIcon[]>> = T[number]['name'];

export * from './svg/app-add-circle-line.icon';
export * from './svg/app-add-fill.icon';
export * from './svg/app-admin-line.icon';
export * from './svg/app-alarm-warning-line.icon';
export * from './svg/app-alert-line.icon';
export * from './svg/app-arrow-down-line.icon';
export * from './svg/app-arrow-down-s-fill.icon';
export * from './svg/app-arrow-down-s-line.icon';
export * from './svg/app-arrow-left-down-line.icon';
export * from './svg/app-arrow-left-line.icon';
export * from './svg/app-arrow-left-right-fill.icon';
export * from './svg/app-arrow-left-s-fill.icon';
export * from './svg/app-arrow-left-s-line.icon';
export * from './svg/app-arrow-left-up-line.icon';
export * from './svg/app-arrow-right-down-line.icon';
export * from './svg/app-arrow-right-line.icon';
export * from './svg/app-arrow-right-s-fill.icon';
export * from './svg/app-arrow-right-s-line.icon';
export * from './svg/app-arrow-right-up-line.icon';
export * from './svg/app-arrow-up-line.icon';
export * from './svg/app-arrow-up-s-fill.icon';
export * from './svg/app-arrow-up-s-line.icon';
export * from './svg/app-bar-chart-2-fill.icon';
export * from './svg/app-calendar-line.icon';
export * from './svg/app-car-components-2.icon';
export * from './svg/app-car-components.icon';
export * from './svg/app-car.icon';
export * from './svg/app-check-fill.icon';
export * from './svg/app-checkbox-circle-fill.icon';
export * from './svg/app-checkbox-circle-line.icon';
export * from './svg/app-close-circle-fill.icon';
export * from './svg/app-close-circle-line.icon';
export * from './svg/app-close-fill.icon';
export * from './svg/app-dashboard-fill.icon';
export * from './svg/app-dashboard-line.icon';
export * from './svg/app-delete-bin-line.icon';
export * from './svg/app-download-line.icon';
export * from './svg/app-error-warning-fill.icon';
export * from './svg/app-error-warning-line.icon';
export * from './svg/app-exchange-box-fill.icon';
export * from './svg/app-eye-line.icon';
export * from './svg/app-file-copy-fill.icon';
export * from './svg/app-file-copy-line.icon';
export * from './svg/app-file-excel-2-fill.icon';
export * from './svg/app-file-excel-2-line.icon';
export * from './svg/app-file-excel-fill.icon';
export * from './svg/app-file-excel-line.icon';
export * from './svg/app-file-pdf-fill.icon';
export * from './svg/app-file-pdf-line.icon';
export * from './svg/app-file-search-line.icon';
export * from './svg/app-filter-2-fill.icon';
export * from './svg/app-filter-fill.icon';
export * from './svg/app-flag-2-fill.icon';
export * from './svg/app-flag-2-line.icon';
export * from './svg/app-flag-fill.icon';
export * from './svg/app-flag-line.icon';
export * from './svg/app-folder-2-line.icon';
export * from './svg/app-folder-5-fill.icon';
export * from './svg/app-gen_fit.icon';
export * from './svg/app-ic-alert.icon';
export * from './svg/app-ic-all_parts_available.icon';
export * from './svg/app-ic-car_component-v2 (5).icon';
export * from './svg/app-ic-car_component-v2.icon';
export * from './svg/app-ic-car-v2.icon';
export * from './svg/app-ic-co2.icon';
export * from './svg/app-ic-dashboard.icon';
export * from './svg/app-ic-factory.icon';
export * from './svg/app-ic-missing_all_parts.icon';
export * from './svg/app-ic-missing_some_parts.icon';
export * from './svg/app-ic-parent.icon';
export * from './svg/app-ic-quality type.icon';
export * from './svg/app-ic-search.icon';
export * from './svg/app-indeterminate-circle-line.icon';
export * from './svg/app-information-line.icon';
export * from './svg/app-iwp_text_doc_blue.icon';
export * from './svg/app-layout-masonry-fill.icon';
export * from './svg/app-layout-masonry-line.icon';
export * from './svg/app-line-chart-fill.icon';
export * from './svg/app-logout-circle-line.icon';
export * from './svg/app-mail-fill.icon';
export * from './svg/app-mail-line.icon';
export * from './svg/app-more-line.icon';
export * from './svg/app-no data illustration.icon';
export * from './svg/app-partchain.icon';
export * from './svg/app-pencil-line.icon';
export * from './svg/app-question-fill.icon';
export * from './svg/app-question-line.icon';
export * from './svg/app-search-fill.icon';
export * from './svg/app-search-line.icon';
export * from './svg/app-settings-3-line.icon';
export * from './svg/app-settings-line.icon';
export * from './svg/app-share-line.icon';
export * from './svg/app-skull-2-fill.icon';
export * from './svg/app-spam-line.icon';
export * from './svg/app-spy-fill.icon';
export * from './svg/app-spy-line.icon';
export * from './svg/app-steering-2-fill.icon';
export * from './svg/app-trace.icon';
export * from './svg/my-icons.model';
