@startuml
skinparam monochrome true
skinparam shadowing false
autonumber "<b>[000]"

actor TraceXApiConsumer
activate TraceXApiConsumer


box "Trace-X FOSS" #LightGrey
participant TraceXAPI
activate TraceXAPI
participant AssetsController
activate AssetsController
participant AssetRepository
activate AssetRepository
participant PersistentAssetsRepository
activate PersistentAssetsRepository
participant JpaAssetsRepository
activate JpaAssetsRepository
database Database

TraceXApiConsumer -> TraceXAPI : GET /assets/as-built
TraceXAPI -> AssetsController :  assets
AssetsController -> AssetRepository :  getAssets(Pageable)
AssetRepository -> PersistentAssetsRepository: getAssets(Pageable)
PersistentAssetsRepository -> JpaAssetsRepository: findAll(Pageable)
JpaAssetsRepository -> Database : success

JpaAssetsRepository <-- Database
PersistentAssetsRepository <-- JpaAssetsRepository
AssetRepository <-- PersistentAssetsRepository
AssetsController <-- AssetRepository
TraceXAPI <-- AssetsController
TraceXApiConsumer <-- TraceXAPI

@enduml
