@startuml
autonumber "<B>[00]"
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName "Architects daughter"
skinparam linetype ortho

actor TraceXApiConsumer
activate TraceXApiConsumer

box "Trace-X FOSS" #LightGrey
participant TraceX
activate TraceX

TraceXApiConsumer -> TraceX : POST /assets/publish
TraceX -> TraceX : Module 2 fails to create EDC Assets or DTR shells
TraceXApiConsumer -> TraceXApiConsumer : GET /assets
TraceXApiConsumer -> TraceX : POST /assets/publish
TraceX -> TraceX : Module 2 process successfully
TraceXApiConsumer -> TraceXApiConsumer : GET /assets




@enduml
