@startuml
autonumber "<B>[00]"
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName "Architects daughter"
skinparam linetype ortho

actor TraceXApiConsumer
activate TraceXApiConsumer

box "Trace-X FOSS" #LightGrey
participant TraceX
activate TraceX

TraceXApiConsumer -> TraceX : POST /assets/publish
TraceX -> TraceX : Module 2
TraceXApiConsumer -> TraceXApiConsumer : GET /assets





@enduml
