@startuml
autonumber "<B>[00]"
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName "Architects daughter"
skinparam linetype ortho

participant FE
participant BE

FE -> BE: request assets: GET/assetsAsxxx
BE --> FE: return assets_as_built OR assets_as_planned
FE -> FE: present assets
FE -> BE: select assets to synchronize: GET/policies
BE --> FE: return policies
FE -> FE: open detailview & assign policy (via dropdown)
FE -> BE: register assets for publishing: POST/assets/publish
BE -> BE: update asset state to IN_SYNC
BE -> BE: trigger 'publish AAS Workflow' (Job scheduler)
BE -> BE: trigger 'data consumption process'
FE -> FE: refresh of FE view
@enduml
