@startuml
|FE|
start
:request assets;
-> GET/assetsAsxxx;
|#Mistyrose|BE|
:return assets_as_built OR assets_as_planned;
-> response;
|FE|
:present assets;
:select assets to synchronize;
-> GET/policies;
|#Mistyrose|BE|
:return policies;
-> response;
|FE|
:open detailview & assign policy (via dropdown);
:register assets for publishing;
-> POST/assets/sync;
|#Mistyrose|BE|
:update asset state to IN_SYNC;
split
:trigger 'publish AAS Workflow' (Job scheduler);
stop
|FE|
split again
:refresh of FE view;
stop
@enduml
