@startuml
autonumber "<B>[00]"
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName "Architects daughter"
skinparam linetype ortho

participant BE
participant EDC
participant Registry
participant Submodels
participant Irs


BE ->> BE: scheduler job
BE ->> BE: receive list of IN_SYNC assets
BE ->> Irs: get policy for assets from policy store: GET/irs/policies
Irs -->> BE: response
BE ->> EDC: create policy in EDC: POST/create/policy
EDC -->> BE: response
BE ->> EDC: create DTR asset in EDC: POST/create/asset
EDC -->> BE: response
BE ->> EDC: create DTR contract in EDC: POST/create/contract
EDC -->> BE: response
BE ->> EDC: create Submodel asset in EDC: POST/create/asset
EDC -->> BE: response
BE ->> EDC: create Submodel contract in EDC: POST/create/contract
EDC -->> BE: response
BE ->> Submodels: create submodel: POST/submodel
Submodels -->> BE:
BE ->> Registry: [017] register shell in registry: POST/semantics/registry
alt Successful DTR shell creation
Registry -->> BE: shell created
BE ->> BE: update asset state PUBLISHED_TO_CORE_SERVICES
BE ->> BE: trigger IRS sync
else DTR shell was not created
Registry -->> BE: create shell not successful or service unavailable
BE ->> BE: update asset state ERROR
end
@enduml
