/*
 * DotAAS Part 2 | HTTP/REST | Registry and Discovery
 * The registry and discovery interface as part of Details of the Asset Administration Shell Part 2
 *
 * The version of the OpenAPI document: Final-Draft
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.eclipse.tractusx.traceability.assets.infrastructure.adapters.feign.registry;

import java.util.List;

public record RegistryShellDescriptorResponse(
	List<RegistryShellDescriptor> items
) {}

record GlobalAssetId(List<String> value) {}

record SpecificAssetId(String key, String value) {}

record RegistryShellDescriptor(
	GlobalAssetId globalAssetId,
	String identification,
	String idShort,
	List<SpecificAssetId> specificAssetIds
) {}

