= Technical context

== Component overview

=== Trace-X API

We provide a REST API that is consumed by Trace-X frontend in order to deliver Trace-X related features such as quality investigations or asset chain visibility.
Since the Trace-X component is the very last component in the Catena-X ecosystem we are mostly dependent on the other services and theirs APIs in other to deliver desired functionalities. The development of the services is not a part of the Trace-X application and each of the system that we utilize exposes a REST API that we consume and interact with directly.

Trace-X is a Spring Boot based application and is secured with the OpenID connector provider Keycloak and OAuth2. This means for the companies that utilize the Trace-X component, it is required to obtain a technical user to be authorized to get access to the external components within the Catena-X ecosystem.

In order to use the Trace-X frontend with the Trace-X backend, users need to authenticate themselves in order to be authorized to get access to the Trace-X.
In the frontend UI users provide valid credentials and the system generates a bearer token that it gets from Keycloak and attaches it to the HTTP header parameter Authorization.
Once a user is authorized and has a proper role in the Trace-X backend, the backend delegates HTTP calls to specific services on their behalf as technical user in order to fulfill specific functionalities.

=== [Outdated] Registry API

[plantuml, target=technical-context-registry, format=svg]
....
include::../../../uml-diagrams/arc42/scope-context/technical-context/aas-api-view.puml[]
....

Trace-X acts as a consumer of the asset administration shell registry component. Trace-X contains a restful client (REST template) that builds a REST call to the mentioned digital twin registry API based on its known URL (the AAS registry URL is configurable in Trace-X).
Requests contain 'assetIds' provided by the component during asset synchronization. Like described in the above section, the security aspect is required in order to achieve a REST call against the AAS Registry. As a response, Trace-X gets the corresponding shells and shell descriptors utilized later for asset synchronization.
The HTTP(s) transport protocol is used for the REST call communication.

=== IRS API

[plantuml, target=technical-context-irs, format=svg]
....
include::../../../uml-diagrams/arc42/scope-context/technical-context/irs-api-view.puml[]
....

Trace-X acts as a consumer of the IRS component. Trace-X contains a restful client (REST template) that build a REST call to the mentioned IRS API based on its known URL (the IRS URL is configurable in Trace-X).
The request contains details required to start an IRS fetch job provided by the component during asset synchronization. Like described in the above section, the security aspect is required in order to achieve a REST call against the IRS. As a response, Trace-X gets the created job id and periodically pulls for the job details that contains assets that will be uploaded to the system.
As mentioned above, the transport protocol HTTP(S) is used for the REST call communication.

=== [Outdated] Portal API

[plantuml, target=technical-context-portal, format=svg]
....
include::../../../uml-diagrams/arc42/scope-context/technical-context/portal-api-view.puml[]
....

Trace-X acts as a consumer of the portal component.
Trace-X contains a restful client (REST template) that builds a REST call to the mentioned Portal API based on its known URL (the Portal URL is configurable in Trace-X).
The portal is used to authenticate users and requests against the backend.
As mentioned above, the transport protocol HTTP(S) is used for the REST call communication.

=== [Outdated] EDC API

[plantuml, target=technical-context-edc, format=svg]
....
include::../../../uml-diagrams/arc42/scope-context/technical-context/edc-api-view.puml[]
....

The Trace-X acts as a consumer and provider of the EDC component.
In Trace-X we communicate with the EDC directly only for the sake of fulfilling the quality notification functionality.
Specific use cases can be viewed in the xref:../runtime-view/index.adoc[Runtime view] section.
For these purposes the integrated EDC clients in Trace-X are responsible for creating restful requests to the EDC component.
As mentioned above, the transport protocol HTTP(S) is used for the REST call communication.
