@startuml
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName "Architects daughter"

title Sequence Diagram: Policy Handling on asset provisioning flow
participant "TraceX" as TraceX
participant "EDC Consumer" as EdcConsumer
participant "EDC Provider (other) " as EdcProvider

TraceX -> TraceX: Publish Asset to Core Services
TraceX -> EdcConsumer: Register policy
EdcConsumer -> EdcProvider: Register policy
EdcProvider -> EdcConsumer: Return ok
EdcConsumer -> TraceX: Return ok
TraceX -> TraceX: Reuse policy for contract definition creation

@enduml
