@startuml
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName "Architects daughter"

title Sequence diagram: Policy handling on asset provisioning flow
participant "Trace-X" as TraceX
participant "EDC Provider (other)" as EdcProvider

activate TraceX
TraceX -> TraceX: Publish asset to core services
TraceX -> EdcProvider: Register policy
EdcProvider --> TraceX: Ok
TraceX -> TraceX: Reuse policy for contract definition creation
@enduml
