@startuml
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName "Architects daughter"

title Sequence diagram: Trace-X interaction with EDC on startup
participant "TraceX" as TraceX
participant "IRS" as IRS
participant "EDC " as EDC

activate TraceX
TraceX -> IRS: Get policies
activate IRS
IRS --> TraceX : Return policies
deactivate IRS
TraceX -> TraceX: Find newest policy of own BPN or default policy
activate TraceX
deactivate TraceX

alt Policy found
    TraceX -> TraceX: Use found policy for EDC policy creation.
    activate TraceX
    TraceX -> EDC : Create notification asset, policy, definition
    deactivate TraceX
else Policy not found
    TraceX -> TraceX: Corrupt state of application
end
@enduml

@startuml
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName "Architects daughter"

title Sequence diagram: Sending notifications
participant "Trace-X" as TraceX
participant "Trace-X IRS Lib" as TraceXIRSLib
participant "IRS " as IRS
participant "EDC " as EDC

activate TraceX
TraceX -> TraceX: ...
TraceX -> EDC: Get catalog
activate EDC
EDC --> TraceX: Return catalog
deactivate EDC
TraceX -> TraceX: Filter for notification type (alert/investigation) & method (update/receive)
activate TraceX
deactivate TraceX
TraceX -> TraceXIRSLib: Validate if catalog policy matches the configured policies in IRS Lib (3 default policies)
activate TraceXIRSLib
TraceXIRSLib --> TraceX: Valid
deactivate TraceXIRSLib
TraceX -> EDC: Send notification
@enduml



