create table asset
(
	id                    varchar(255) not null,
	customer_part_id      varchar(255),
	id_short              varchar(255),
	manufacturer_id       varchar(255),
	manufacturer_name     varchar(255),
	manufacturer_part_id  varchar(255),
	manufacturing_country varchar(255),
	manufacturing_date    timestamp,
	name_at_customer      varchar(255),
	name_at_manufacturer  varchar(255),
	quality_type          integer,
	supplier_part         boolean      not null default (true),
	batch_id              varchar(255),
	part_instance_id      varchar(255),
	primary key (id)
);

create table asset_child_descriptors
(
	asset_entity_id varchar(255) not null,
	id              varchar(255),
	id_short        varchar(255)
);

alter table if exists asset_child_descriptors add constraint fk_asset foreign key (asset_entity_id) references asset;

create table shell_descriptor
(
	id                   int8 generated by default as identity,
	created              timestamptz not null,
	updated              timestamptz not null,
	shell_descriptor_id  text        not null unique,
	global_asset_id      text        not null unique,
	batch_id             VARCHAR(255),
	id_short             VARCHAR(255),
	part_instance_id     VARCHAR(255),
	manufacturer_part_id VARCHAR(255),
	manufacturer_id      VARCHAR(255)
);
