ALTER TABLE alert
    ALTER COLUMN side SET DATA TYPE VARCHAR(50);
ALTER TABLE alert
    ALTER COLUMN status SET DATA TYPE VARCHAR(50);
ALTER TABLE investigation
    ALTER COLUMN side SET DATA TYPE VARCHAR(50);
ALTER TABLE investigation
    ALTER COLUMN status SET DATA TYPE VARCHAR(50);
