## Copyright (c) 2023 Contributors to the Eclipse Foundation
##
## See the NOTICE file(s) distributed with this work for additional
## information regarding copyright ownership.
##
## This program and the accompanying materials are made available under the
## terms of the Apache License, Version 2.0 which is available at
## https://www.apache.org/licenses/LICENSE-2.0. *
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
## WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
## License for the specific language governing permissions and limitations
## under the License.
##
## * SPDX-License-Identifier: Apache-2.0

create table assets_investigations
(
	investigation_id int8         not null,
	asset_id         varchar(255) not null
);

create table assets_notifications
(
	notification_id varchar(255) not null,
	asset_id        varchar(255) not null
);

create table investigation
(
	id           int8 generated by default as identity,
	bpn          varchar(255),
	close_reason varchar(255),
	created      timestamp,
	description  varchar(255),
	status       int4,
	updated      timestamp,
	primary key (id)
);

create table notification
(
	id                        varchar(255) not null,
	contract_agreement_id     varchar(255),
	edc_url                   varchar(255),
	notification_reference_id varchar(255),
	receiver_bpn_number       varchar(255),
	sender_bpn_number         varchar(255),
	investigation_id          int8,
	primary key (id)
);

alter table if exists assets_investigations
	add constraint fk_asset_entity foreign key (asset_id) references asset;

alter table if exists assets_investigations
	add constraint fk_investigation foreign key (investigation_id) references investigation;

alter table if exists assets_notifications
	add constraint fk_notification foreign key (notification_id) references notification;

alter table if exists notification
	add constraint fk_investigation foreign key (investigation_id) references investigation;
