@startuml

autonumber "<B>[00]"
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName "Architects daughter"
skinparam linetype ortho

title Policies: Send and receive parts

actor "Admin \n [A]" as AA
actor User
participant "Trace-X \n [A]" as TXA
participant "PolicyStore \n [A]" as PSA
participant "Digital Twin Registry \n [A]" as DTRA
participant "EDC \n [A]" as EDCA
participant "EDC \n [B]" as EDCB
participant "IRS \n [B]" as IRSB
participant "PolicyStore \n [B]" as PSB
participant "Trace-X \n [B]" as TXB

AA -> TXA: create policy
activate TXA
TXA -> PSA: create policy
activate PSA
TXA <-- PSA: 201 policy created
deactivate PSA
AA <-- TXA: policy created
deactivate TXA

...

User -> TXA: import parts (POST /assets/import)
activate TXA
User <-- TXA: 200 success
deactivate TXA

...

User -> TXA: publish selected parts in transient state (POST /assets/publish)
activate TXA
User <-- TXA: request for policy
User --> TXA: select policy to be used

loop selected parts
    TXA -> EDCA: create part (POST /v3/assets)
    activate EDCA
    TXA <-- EDCA: 200 part created
    deactivate EDCA

    opt policyDefintion does not exist
        TXA -> EDCA: create policyDefintion (/management/v2/policyDefintions)
        activate EDCA
        TXA <-- EDCA: policyDefintion created
        deactivate EDCA
    end opt

    TXA -> EDCA: create contractDefinition with policy (/management/v2/contractDefinitions)
    activate EDCA
    TXA <-- EDCA: contractDefinition created
    deactivate EDCA

    TXA -> DTRA: create Asset Administration Shell Descriptor
    activate DTRA
    TXA <-- DTRA: 201 Asset Administration Shell Descriptor created
    deactivate DTRA

    deactivate TXA
end

...

AB -> TXB: create policy for BPNL of Trace-X [A]
activate TXB
TXB -> PSB: create policy
activate PSB
TXB <-- PSB: 201 policy created
deactivate PSB
AB <-- TXB: policy created
deactivate TXB

...

TXB -> TXB: synchronize parts
activate TXB

TXB -> DTRA: get Asset Administration Shell Descriptors
activate DTRA
TXB <-- DTRA: Asset Administration Shell Descriptors
deactivate DTRA

TXB -> TXB: Extract globalAssetIds

TXB -> IRSB: Register sync job for all globalAssetIds
activate IRSB
IRSB -> EDCA: GET /v2/catalog/request of Trace-X A
note left
    (/v2/catalog/request/querySpec/filterExpression[id:digitalTwinRegistry])
end note
activate EDCA
EDCA --> IRSB: return catalogOffer
deactivate EDCA
IRSB -> PSB:  get policy for BPNL
activate PSB
IRSB <-- PSB: policy for BPNL
deactivate PSB

loop each part
    IRSB -> IRSB: compare catalogOffer policy with company policy for BPNL
    alt policies match
        IRSB -> EDCB: start contract negotiation
        EDCB -> EDCA:  contract negotiation
        EDCB <-- EDCA: contractAgreement
        IRSB <-- EDCB: contractAgreement
        ref over IRSB, TXB: import part data -> data consumption
        else policies does not match
            IRSB -> IRSB: create tombstone with policy
            TXB <-- IRSB: job response
    end
end
TXB <-- IRSB: job response

@enduml
