@startuml
'https://plantuml.com/sequence-diagram
autonumber
title Policies: Send notification

actor Admin
actor User
participant "Trace-X A" as TXA
participant "EDC A" as EDCA
participant "EDC B" as EDCB

Admin -> TXA: create policies
...
User -> TXA: send notification to receiver BPN
activate TXA
TXA -> EDCB: get catalog of receiver BPN
activate EDCB
EDCB --> TXA: catalog
deactivate EDCB
TXA -> TXA: extract required policy definition from catalog
TXA -> TXA: get own policy definition for receiver BPN
activate TXA
TXA --> TXA: valid policyDefinition
deactivate TXA
TXA -> TXA: compare policy definitions
alt policies match
TXA --> EDCB: contract agreement
TXA --> EDCA: contract agreement
TXA -> EDCB: send notification
else
TXA --> User: error: policies don't match
end
@enduml
