@startuml
autonumber "<B>[00]"
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName "Architects daughter"
skinparam linetype ortho


title Policies: No policies defined for Receiver BPNL when sending notifications

actor Admin
actor User
participant "Trace-X \n [A]" as TraceX
participant "Receiver EDC \n [B]" as EDC
participant "Policy Store \n [A]" as PSA

Admin -> TraceX: create policies
...
User -> TraceX: send notification to receiver BPN
activate TraceX
TraceX -> EDC: get catalog of receiver BPN
activate EDC
EDC --> TraceX: return CatalogOffer
deactivate EDC
TraceX -> TraceX: extract required policy from CatalogOffer
TraceX -> PSA: get policy definition for receiver BPN
autonumber stop
TraceX <--  PSA : return policy of BPNL [B]
autonumber resume
activate TraceX
opt no policyDefinition for receiver BPN
    TraceX --> TraceX: use default policy
end opt
deactivate TraceX
TraceX -> TraceX: compare policy definition of CatalogOffer with policy of BPNL
alt policies don't match
TraceX --> User: error: policies don't match
deactivate TraceX
...
Admin -> TraceX: add policy for receiver BPN
...
User -> TraceX: resend notification to receiver BPN
ref over User, Admin, TraceX, EDC: send notification
end
@enduml
