@startuml

autonumber "<B>[00]"
skinparam monochrome true
skinparam shadowing false
skinparam defaultFontName "Architects daughter"
skinparam linetype ortho

title Policies: Send and receive parts

actor "Admin \n [A]" as AA
actor User
participant "Trace-X \n [A]" as TXA
participant "PolicyStore \n [A]" as PSA
participant "Digital Twin Registry \n [A]" as DTRA
participant "EDC \n [A]" as EDCA
participant "Digital Twin Registry \n [B]" as DTRB
participant "EDC \n [B]" as EDCB
participant "IRS \n [B]" as IRSB
participant "PolicyStore \n [B]" as PSB
participant "Trace-X \n [B]" as TXB
actor "Admin B" as AB

AA -> TXA: create policy
note left
    create policy used for publishing
       company parts [POLICY_TRACEX-PUBLISH_ASSETS]
end note
activate TXA
TXA -> PSA: create policy for BPNL
TXA <-- PSA: 201 policy created
AA <-- TXA: policy created
deactivate TXA

AB -> TXB: create policy
activate TXB


note right
    create policy for
    BPNL of Trace-X [A]
    [POLICY_BPNL_TRACEX_A]
end note
AB <-- TXB: policy created
deactivate TXB

...
User -> TXA: import parts (POST /assets/import)
activate TXA
User <-- TXA: ok
...

User -> TXA: publish selected parts (POST /assets/publish)

User <-- TXA: request for policy

User --> TXA: select policy to be used

TXA -> EDCA: PolicyDefinition exists
TXA <-- EDCA: return PolicyDefinition exists
opt PolicyDefinition exists
TXA -> EDCA: create PolicyDefinition (/management/v2/policydefinitions)
TXA <-- EDCA: PolicyDefinition created
else

end opt

loop selected parts

TXA -> DTRA: create asset /shell-descriptors
note left
    create asset in DTR
end note
TXA <-- DTRA: 201 : Asset Administration Shell Descriptor created successfully

TXA -> EDCA: create asset (POST /v3/assets)
note left
    create CatalogOffer in EDC
end note
TXA <-- EDCA: 200 Asset was created successfully.

TXA -> EDCA: create ContractDefinition (/management/v2/contractdefinitions) with policy
note left
    create ContractDefinition in EDC
end note
TXA <-- EDCA: ContractDefinition created

end


deactivate TXA
...
TXB -> TXB: synchronize parts (assets/as-$/sync)
note left
    different endpoints for sync as-built and as-planned assets
end note
activate TXB
TXB -> DTRB: GET Asset Administration Shell Descriptors
activate DTRB
TXB <-- DTRB: 200 Requested Asset Administration Shell Descriptors
deactivate DTRB

TXB -> IRSB: Register job (GET /irs/jobs)
activate IRSB
IRSB -> EDCA: GET /v2/catalog/request of Trace-X A
note left
    (/v2/catalog/request/querySpec/filterExpression[id:digitalTwinRegistry])
end note
activate EDCA
EDCA --> IRSB: return catalog
deactivate EDCA
IRSB -> IRSB: extract policy definitions from catalog
IRSB -> PSB:  get policies for BPNL

activate PSB
IRSB <-- PSB: policy for BPNL
deactivate PSB

loop each part
IRSB -> IRSB: compare ContractOffer policy with Company policy for BPNL
alt policies match
IRSB -> EDCB: start contract negotiation
EDCB -> EDCA:  contract negotiation
EDCB <-- EDCA: ok contractAgreement
IRSB <-- EDCB: ok contractAgreement
ref over IRSB, TXB: data consumption
end
end

TXB <-- IRSB : calback job response

@enduml
