= Installation

The Trace-X Helm Backend repository can be found here:

https://eclipse-tractusx.github.io/traceability-foss-backend/index.yaml

The Trace-X Helm Frontend repository can be found here:

https://eclipse-tractusx.github.io/traceability-foss-frontend/index.yaml

Use the latest release of the "trace-x-helm" chart.
It contains all required dependencies.

Supply the required configuration properties (see chapter xref:configuration.adoc#_configuration[Configuration]) in a values.yaml file or override the settings directly.

== Deployment using Helm

Add the Trace-X Backend Helm repository:

[listing]
$ helm repo add traceability-foss-backend https://eclipse-tractusx.github.io/traceability-foss-backend
$ helm repo add traceability-foss-frontend https://eclipse-tractusx.github.io/traceability-foss-frontend

Then install the Helm chart into your cluster:

[listing]
$ helm install -f your-values.yaml traceability-foss-backend traceability-foss-backend/traceability-foss-backend
$ helm install -f your-values.yaml traceability-foss-frontend traceability-foss-frontend/traceability-foss-frontend

== Dependent values

Following values needs to match in order for application to start and have valid PostgreSQL connection:

[source,yaml]
datasource:
    password: # database password

[source,yaml]
postgresql:
    auth:
        password: # database password

== Deployment using ArgoCD

Create a new Helm chart and use Trace-X as a dependency.

[source,yaml]
dependencies:
  - name: traceability-foss-frontend
    alias: frontend
    version: x.x.x
    repository: "https://eclipse-tractusx.github.io/traceability-foss-frontend/"
  - name: traceability-foss-backend
    alias: backend
    version: x.x.x
    repository: "https://eclipse-tractusx.github.io/traceability-foss-backend/"

Then provide your configuration as the values.yaml of that chart.

Create a new application in ArgoCD and point it to your repository / Helm chart folder.
