= Installation

The Trace-X Helm repository can be found here:

https://eclipse-tractusx.github.io/traceability-foss/index.yaml

Use the latest release of the "trace-x-helm" chart.
It contains all required dependencies.

Supply the required configuration properties (see chapter xref:configuration.adoc#_configuration[Configuration]) in a values.yaml file or override the settings directly.

== Deployment using Helm

Add the Trace-X Helm repository:

[listing]
$ helm repo add traceability-foss https://eclipse-tractusx.github.io/traceability-foss

Then install the Helm chart into your cluster:

[listing]
$ helm install -f your-values.yaml traceability-foss traceability-foss/traceability-foss


== Dependent values

Following values need to match in order for application to start and have a valid PostgreSQL connection:

[source,yaml]
datasource:
    password: # database password

[source,yaml]
postgresql:
    auth:
        password: # database password

== Deployment using ArgoCD

Create a new Helm chart and use Trace-X as a dependency.

[source,yaml]
dependencies:
  - name: traceability-foss
    alias: traceability-foss
    version: x.x.x
    repository: "https://eclipse-tractusx.github.io/traceability-foss/"

Then provide your configuration as the values.yaml of that chart.

Create a new application in ArgoCD and point it to your repository / Helm chart folder.
