[#_portal_configuration]
= Portal Configuration
//:allow-uri-read:
:icons: font
:icon-set: fas

The following process is required to successfully connect to the portal:

== Company Registration
https://portal.int.demo.catena-x.net/documentation[How To]

=== Additional info
Each instance of trace-x reflects an own company, which is associated with one BPN.

== User Registration
https://portal.int.demo.catena-x.net/documentation/[How To]

=== Additional info
The user registration is a self service. Each user can have one or multiple trace-x roles assigned.

== Connector Registration
https://portal.int.demo.catena-x.net/documentation/[How To]

=== Additional info
A connector in the context of trace-x is a Eclipse-Dataspace-Connector. This connector needs to be configured by the public controlplane url.

== App Registration
https://portal.int.demo.catena-x.net/documentation/[How To]

=== Additional info
A connector in the context of trace-x is a Eclipse-Dataspace-Connector. This connector needs to be configured by the public controlplane url.

== Create App Subscription
https://portal.int.demo.catena-x.net/documentation/[How To]

=== Additional info
An app subscription is necessary to be able to setup a frontend url which will be authorized through keycloak and accessible with the portal.

== Activate App Subscription
https://portal.int.demo.catena-x.net/documentation/[How To]

=== Additional info
The app subscription needs to be activated from all instances which want to participate in the trace-x use case.

== Retrieve Wallet Configuration
https://portal.int.demo.catena-x.net/documentation/[How To]
