[#_portal_configuration]
= Portal configuration
//:allow-uri-read:
:icons: font
:icon-set: fas

The following process is required to successfully connect to the portal:

- Company registration with BPN, Company Name

- User Registration with E-Mail

- Get e-mail to reset your password

- Reset the password and log in

- Make sure your user has the role App Management

- Navigate to App Overview

- Create app

- Choose a selection of managed roles which is necessary (currently: BPDM, Dataspace Discovery, Semantic Model Management, Identity Wallet Management)

- Wait for app approval by portal

- Subscribe to the app

-  As app creator navigate to subscription management - click on configure

-  Add the frontend url of the application and click approve

-  Save technical user and secret

-  Navigate to Register Connector

-  Add managed connector

-  Select existing technical user (from app subscription)

-  Enter name "EDC Provider A"

-  Enter base url of controlplane (EDC)

-  Confirm

-  Go to other company which want to participate (subscribe)

-  Login and navigate to app overview

-  Search for the app created

-  Subscribe to the app

-  Go to the app creator company

-  Navigate to the inbox of the portal

-  Click on the nav link to give approval for the company which want to subscribe

-  Enter name "EDC Provider B"

-  Enter base url of controlplane (EDC)

-  Make sure to popuplate the new client id, secrets and app id within trace-x for each company to let it run properly with the new portal configuration.

== Company registration
https://portal.int.demo.catena-x.net/documentation[How-to]

=== Additional info
Each instance of trace-x reflects an own company, which is associated with one BPN.

== User registration
https://portal.int.demo.catena-x.net/documentation/[How-to]

=== Additional info
The user registration is a self-service. Each user can have one or multiple Trace-X roles assigned.

== Connector registration
https://portal.int.demo.catena-x.net/documentation/[How-to]

=== Additional info
A connector in the context of trace-x is a Eclipse-Dataspace-Connector. This connector needs to be configured by the public controlplane URL.

== App registration
https://portal.int.demo.catena-x.net/documentation/[How-to]

=== Additional info
A connector in the context of trace-x is a Eclipse-Dataspace-Connector. This connector needs to be configured by the public controlplane URL.

== Create app subscription
https://portal.int.demo.catena-x.net/documentation/[How-to]

=== Additional info
An app subscription is necessary to be able to setup a frontend url which will be authorized through keycloak and accessible with the portal.

== Activate App subscription
https://portal.int.demo.catena-x.net/documentation/[How-to]

=== Additional info
The app subscription needs to be activated from all instances which want to participate in the Trace-X use case.

== Retrieve wallet configuration
https://portal.int.demo.catena-x.net/documentation/[How-to]
