[#_portal_configuration]
= Portal configuration
//:allow-uri-read:
:icons: font
:icon-set: fas

The following process is required to successfully connect to the portal:

== Company registration
https://portal.int.demo.catena-x.net/documentation[How-to]

=== Additional info
Each instance of trace-x reflects an own company, which is associated with one BPN.

== User registration
https://portal.int.demo.catena-x.net/documentation/[How-to]

=== Additional info
The user registration is a self-service. Each user can have one or multiple Trace-X roles assigned.

== Connector registration
https://portal.int.demo.catena-x.net/documentation/[How-to]

=== Additional info
A connector in the context of trace-x is a Eclipse-Dataspace-Connector. This connector needs to be configured by the public controlplane URL.

== App registration
https://portal.int.demo.catena-x.net/documentation/[How-to]

=== Additional info
A connector in the context of trace-x is a Eclipse-Dataspace-Connector. This connector needs to be configured by the public controlplane URL.

== Create app subscription
https://portal.int.demo.catena-x.net/documentation/[How-to]

=== Additional info
An app subscription is necessary to be able to setup a frontend url which will be authorized through keycloak and accessible with the portal.

== Activate App subscription
https://portal.int.demo.catena-x.net/documentation/[How-to]

=== Additional info
The app subscription needs to be activated from all instances which want to participate in the Trace-X use case.

== Retrieve wallet configuration
https://portal.int.demo.catena-x.net/documentation/[How-to]
