name: Debug Actions

on:
  push:
    branches: [ debug ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Echo variables
      run: |
        set
      env:
        SONAR_TEST: ${{ vars.SONAR_ORGANIZATION }}
        SONAR_SECRET_TEST: ${{ secrets.SONAR_ORGANIZATION }}
