name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      # if you need to change image please make sure use the same version in all places
      # (here and in cypress/Dockerfile)
      image: cypress/browsers:node16.16.0-chrome107-ff107-edge
      options: --user 1001

    # Install YARN dependencies, cache them correctly
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run yarn install
        uses: Borales/actions-yarn@v4.2.0
        with:
          cmd: install # will run `yarn install` command

  cypress-run-chrome:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.16.0-chrome107-ff107-edge
      options: --user 1001
    needs: install

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Cypress run all tests
        uses: cypress-io/github-action@v5.0.8 # use the explicit version number
        with:
          start: npm start
          wait-on: "http://localhost:4200"
          wait-on-timeout: 120
          browser: chrome

      - name: Archive cypress artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress generated files - chrome
          path: |
            cypress/videos/
            cypress/screenshots/

  cypress-run-firefox:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.16.0-chrome107-ff107-edge
      options: --user 1001
    needs: install

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Cypress run all tests
        uses: cypress-io/github-action@v5.0.8 # use the explicit version number
        with:
          start: npm start
          wait-on: "http://localhost:4200"
          wait-on-timeout: 120
          browser: firefox

      - name: Archive cypress artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress generated files - firefox
          path: |
            cypress/videos/
            cypress/screenshots/

  cypress-run-webkit:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: install

    steps:
      - name: Checkout
        uses: actions/checkout@v3

# commented because if we use it here, we face with that problem:
# "http://localhost:4200 timed out on retry 151 of 5, elapsed 150449ms, limit 150000ms
#  Error: connect ECONNREFUSED 127.0.0.1:4200"

#      - name: Use Node.js 18.x
#        uses: actions/setup-node@v3
#        with:
#          node-version: 18.x

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      # https://docs.cypress.io/guides/guides/launching-browsers#Linux-Dependencies
      - name: Install additional dependencies
        run: npx playwright install --with-deps webkit

      - name: Cypress run all tests
        uses: cypress-io/github-action@v5.0.8 # use the explicit version number
        with:
          start: npm start
          wait-on: "http://localhost:4200"
          wait-on-timeout: 120
          browser: webkit

      - name: Archive cypress artifacts
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress generated files - webkit
          path: |
            cypress/videos/
            cypress/screenshots/
